### ISSUE TITLE
Test program hangs indefinitely

### ISSUE THREAD

**Issue by trmckay** [atsuoishimoto/python-raindropio#3]
Running the following test program (with my API token substituded in, of course) hangs forever:

```python
from raindropio import API, Collection
api = API(raidrop_access_token)

c = Collection.create(api, title="Sample collection")
print(c.title)
```

- Installed with pip3
- Python is up to date (3.9.1)
- Platform: Linux
- Tested with Python 3.9 and 3.8

Pressing ctrl-c gives the following stack trace, offering some clues about where it's getting stuck.

```
Traceback (most recent call last):
  File "/home/trevor/rdtest", line 4, in <module>
    c = Collection.create(api, title="Sample collection")
  File "/home/trevor/.local/lib/python3.9/site-packages/raindropio/models.py", line 145, in create
    item = api.post(URL, json=args).json()["item"]
  File "/home/trevor/.local/lib/python3.9/site-packages/raindropio/api.py", line 171, in post
    ret = self.session.post(url, headers=self._request_headers(), data=json)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

**Comment by atsuoishimoto** [comment]
Thank you for reporting

Your code works for me(Python3.8/3.9, Linux). 
From traceback, it looks Python waiting for a connection to the raindopio server established. So I suspect network issues involved in your environment.  May be some firewalls or proxies needs to be configured to connect to the https://api.raindrop.io ?

**Comment by trmckay** [comment]
You're right. For some reason I can browse the internet just fine, but ping/etc. does not work. I'll close this issue since it's obviously on my end.
